/*
 * IR Key mapping for marvell Remote Controller
 */
static struct ir_keymap keymap_tab[] = {
	MAKE_IR_KEYMAP(MV_IR_KEY_NULL,          0, KEY_RESERVED), /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_POWER,	        0, KEY_POWER),
	MAKE_IR_KEYMAP(MV_IR_KEY_OPENCLOSE,     0, KEY_OPEN),
	MAKE_IR_KEYMAP(MV_IR_KEY_BEGIN_PAIRING, 0, KEY_START_PAIRIING),
	MAKE_IR_KEYMAP(MV_IR_KEY_RECOVERY,      0, KEY_RECOVERY),

	/* digital keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_1,       0, KEY_1),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_2,       0, KEY_2),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_3,       0, KEY_3),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_4,       0, KEY_4),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_5,       0, KEY_5),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_6,       0, KEY_6),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_7,       0, KEY_7),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_8,       0, KEY_8),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_9,       0, KEY_9),
	MAKE_IR_KEYMAP(MV_IR_KEY_DIGIT_0,       0, KEY_0),

	/* for BD */
	MAKE_IR_KEYMAP(MV_IR_KEY_INFO,          0, KEY_INFO),
	MAKE_IR_KEYMAP(MV_IR_KEY_SETUPMENU,     0, KEY_HOME),
	MAKE_IR_KEYMAP(MV_IR_KEY_CANCEL,        0, KEY_CANCEL), /* no key */

	MAKE_IR_KEYMAP(MV_IR_KEY_DISCMENU,      0, KEY_CONTEXT_MENU),
	MAKE_IR_KEYMAP(MV_IR_KEY_TITLEMENU,     0, KEY_TITLE),
	MAKE_IR_KEYMAP(MV_IR_KEY_SUBTITLE,      0, KEY_SUBTITLE),
	MAKE_IR_KEYMAP(MV_IR_KEY_ANGLE,         0, KEY_ANGLE),
	MAKE_IR_KEYMAP(MV_IR_KEY_AUDIO,         0, KEY_AUDIO),
	MAKE_IR_KEYMAP(MV_IR_KEY_SEARCH,        0, KEY_SEARCH),
	MAKE_IR_KEYMAP(MV_IR_KEY_ZOOM,          0, KEY_ZOOM),
	MAKE_IR_KEYMAP(MV_IR_KEY_DISPLAY,       0, KEY_SCREEN),

	MAKE_IR_KEYMAP(MV_IR_KEY_REPEAT,        0, KEY_MEDIA_REPEAT),
	MAKE_IR_KEYMAP(MV_IR_KEY_REPEAT_AB,     0, KEY_AB),
	MAKE_IR_KEYMAP(MV_IR_KEY_MARKER,        0, KEY_MARKER),
	MAKE_IR_KEYMAP(MV_IR_KEY_EXIT,          0, KEY_EXIT),
	MAKE_IR_KEYMAP(MV_IR_KEY_A,             0, KEY_RED),
	MAKE_IR_KEYMAP(MV_IR_KEY_B,             0, KEY_GREEN),
	MAKE_IR_KEYMAP(MV_IR_KEY_C,             0, KEY_YELLOW),
	MAKE_IR_KEYMAP(MV_IR_KEY_D,             0, KEY_BLUE),

	/* IR misc around ENTER */
	MAKE_IR_KEYMAP(MV_IR_KEY_CLEAR,         0, KEY_CLEAR),
	MAKE_IR_KEYMAP(MV_IR_KEY_VIDEO_FORMAT,  0, KEY_VIDEO),
	MAKE_IR_KEYMAP(MV_IR_KEY_STEP,          0, KEY_STEP),
	MAKE_IR_KEYMAP(MV_IR_KEY_RETURN,        0, KEY_ESC),

	/* up down left right enter */
	MAKE_IR_KEYMAP(MV_IR_KEY_UP,            0, KEY_UP),
	MAKE_IR_KEYMAP(MV_IR_KEY_DOWN,          0, KEY_DOWN),
	MAKE_IR_KEYMAP(MV_IR_KEY_LEFT,          0, KEY_LEFT),
	MAKE_IR_KEYMAP(MV_IR_KEY_RIGHT,         0, KEY_RIGHT),
	MAKE_IR_KEYMAP(MV_IR_KEY_ENTER,         0, KEY_ENTER),

	/* for BD */
	MAKE_IR_KEYMAP(MV_IR_KEY_SLOW,          0, KEY_SLOW),
	MAKE_IR_KEYMAP(MV_IR_KEY_PAUSE,         0, KEY_PAUSE),
	MAKE_IR_KEYMAP(MV_IR_KEY_PLAY,          0, KEY_PLAY),
	MAKE_IR_KEYMAP(MV_IR_KEY_STOP,          0, KEY_STOP),
	MAKE_IR_KEYMAP(MV_IR_KEY_PLAY_PAUSE,    0, KEY_PLAYPAUSE), /* no key */

	MAKE_IR_KEYMAP(MV_IR_KEY_SKIP_BACKWARD, 0, KEY_PREVIOUS),
	MAKE_IR_KEYMAP(MV_IR_KEY_SKIP_FORWARD,  0, KEY_NEXT),
	MAKE_IR_KEYMAP(MV_IR_KEY_SLOW_BACKWARD, 0, KEY_RESERVED),  /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_SLOW_FORWARD,  0, KEY_RESERVED),  /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_FAST_BACKWARD, 0, KEY_REWIND),
	MAKE_IR_KEYMAP(MV_IR_KEY_FAST_FORWARD,  0, KEY_FORWARD),

	/* bottom keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_F1,            0, KEY_F1),
	MAKE_IR_KEYMAP(MV_IR_KEY_F2,            0, KEY_F2),
	MAKE_IR_KEYMAP(MV_IR_KEY_F3,            0, KEY_F3),
	MAKE_IR_KEYMAP(MV_IR_KEY_F4,            0, KEY_F4),
	MAKE_IR_KEYMAP(MV_IR_KEY_F5,            0, KEY_F5),
	MAKE_IR_KEYMAP(MV_IR_KEY_F6,            0, KEY_F6),
	MAKE_IR_KEYMAP(MV_IR_KEY_F7,            0, KEY_F7),
	MAKE_IR_KEYMAP(MV_IR_KEY_F8,            0, KEY_F8),

	/* for future */
	MAKE_IR_KEYMAP(MV_IR_KEY_VOL_PLUS,      0, KEY_VOLUMEUP),   /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_VOL_MINUS,     0, KEY_VOLUMEDOWN), /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_VOL_MUTE,      0, KEY_MUTE),       /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_CHANNEL_PLUS,  0, KEY_CHANNELUP),  /* no key */
	MAKE_IR_KEYMAP(MV_IR_KEY_CHANNEL_MINUS, 0, KEY_CHANNELDOWN),/* no key */

	/* obsoleted keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_MENU,          0, KEY_MENU),
	MAKE_IR_KEYMAP(MV_IR_KEY_INPUTSEL,      0, KEY_RESERVED),
	MAKE_IR_KEYMAP(MV_IR_KEY_ANYNET,        0, KEY_RESERVED),
	MAKE_IR_KEYMAP(MV_IR_KEY_TELEVISION,    0, KEY_TV),
	MAKE_IR_KEYMAP(MV_IR_KEY_CHANNEL_LIST,  0, KEY_RESERVED),
	MAKE_IR_KEYMAP(MV_IR_KEY_TVPOWER,       0, KEY_RESERVED),

	/* customization keys */
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM0,       0, KEY_CUSTOM0),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM1,       0, KEY_CUSTOM1),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM2,       0, KEY_CUSTOM2),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM3,       0, KEY_CUSTOM3),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM4,       0, KEY_CUSTOM4),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM5,       0, KEY_CUSTOM5),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM6,       0, KEY_CUSTOM6),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM7,       0, KEY_CUSTOM7),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM8,       0, KEY_CUSTOM8),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM9,       0, KEY_CUSTOM9),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM10,      0, KEY_CUSTOM10),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM11,      0, KEY_CUSTOM11),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM12,      0, KEY_CUSTOM12),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM13,      0, KEY_CUSTOM13),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM14,      0, KEY_CUSTOM14),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM15,      0, KEY_CUSTOM15),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM16,      0, KEY_CUSTOM16),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM17,      0, KEY_CUSTOM17),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM18,      0, KEY_CUSTOM18),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM19,      0, KEY_CUSTOM19),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM20,      0, KEY_CUSTOM20),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM21,      0, KEY_CUSTOM21),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM22,      0, KEY_CUSTOM22),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM23,      0, KEY_CUSTOM23),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM24,      0, KEY_CUSTOM24),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM25,      0, KEY_CUSTOM25),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM26,      0, KEY_CUSTOM26),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM27,      0, KEY_CUSTOM27),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM28,      0, KEY_CUSTOM28),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM29,      0, KEY_CUSTOM29),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM30,      0, KEY_CUSTOM30),
	MAKE_IR_KEYMAP(MV_IR_KEY_CUSTOM31,      0, KEY_CUSTOM31),
};
