#
# Makefile for the Linux Bluetooth UCD modules layer
#

obj-$(CONFIG_BT_UCD_INPUT) += ucd_input.o
obj-$(CONFIG_BT_UCD_SONY_INPUT) += ucd_input_sony.o
obj-$(CONFIG_BT_UCD_MARVELL_INPUT) += ucd_input_marvell.o

